services:
  docs:
    build: .
    ports:
      - "8007:8007"
    volumes:
      - ./:/docs
    environment:
      - PORT=8007
      - HOST=0.0.0.0
      - SPHINXOPTS="-D html_host=0.0.0.0 -D html_port=8007"
    command: make livehtml